<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: rook
 * Date: Sat, 06 Jul 2019 00:53:42 +0000
 */

$conf['title'] = 'Lord Sroff Freight Wiki';
$conf['tagline'] = 'A Home for our Star Wars Minos Cluster Universe';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
