# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 19 Jun 2019 18:59:10 +0000
*               @ALL          1
*               @user         8
